seed: 42
model:
  image_encoder: "microsoft/resnet-50"
  text_encoder: "facebook/opt-350m"
  frozen_image_encoder: false
  frozen_text_encoder: false
  pretrained_text_encoder: true
  num_image_tokens: 2
  # enable_gradient_checkpointing: true

trainer:
  gpus: 1
  max_epochs: 5
  precision: 16
  gradient_clip_val: 1.0
  val_check_interval: 1.0
  resume_from_checkpoint: null
  accumulate_grad_batches: 4
  log_every_n_steps: 1
  # detect_anomaly: true  # Helps detect gradient issues
  # track_grad_norm: 2  # Track gradient norms

# data loader
loader:
  batch_size: 2
  pin_memory: false
  num_workers: 16

# logger (tensorboard)
logger:
  name: run-full-DCC-1.0
  version: 1.0.0
  save_dir: ~/logs

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_perplexity"
  mode: "min"

# resume training
checkpoint_path: ckpt

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - _self_
  - dataset: DCC
  - optimizer: Frozen
  - override hydra/job_logging: disabled
