_wandb:
    value:
        cli_version: 0.19.0
        m:
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 55
                - 63
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 55
                - 63
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.5
            "5": 0.19.0
            "6": 4.20.1
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
checkpoint/dirpath:
    value: /teamspace/studios/this_studio/Frozen-Interleaved/frozen/wandb/run-20241211_161917-5dcwyk2t/files/checkpoints
checkpoint/mode:
    value: min
checkpoint/monitor:
    value: val_perplexity
checkpoint/save_last:
    value: true
checkpoint/save_top_k:
    value: 1
checkpoint/verbose:
    value: true
checkpoint_path:
    value: ckpt
dataset/name:
    value: DCC
dataset/num_image_tokens:
    value: 2
dataset/path:
    value: /teamspace/studios/this_studio/DialogCC/DialogCC
loader/batch_size:
    value: 16
loader/num_workers:
    value: 16
loader/pin_memory:
    value: false
logger/name:
    value: run-full-DCC-1.0
logger/save_dir:
    value: ~/logs
logger/version:
    value: 1.0.0
model/frozen_image_encoder:
    value: false
model/frozen_text_encoder:
    value: true
model/image_encoder:
    value: microsoft/resnet-50
model/num_image_tokens:
    value: 2
model/pretrained_text_encoder:
    value: true
model/text_encoder:
    value: facebook/opt-350m
optimizer/algorithm:
    value: Adam
optimizer/params/betas:
    value:
        - 0.9
        - 0.95
optimizer/params/eps:
    value: 1e-06
optimizer/params/lr:
    value: 0.0003
seed:
    value: 42
trainer/gpus:
    value: 1
trainer/gradient_clip_val:
    value: 1
trainer/max_epochs:
    value: 5
trainer/precision:
    value: 16
trainer/resume_from_checkpoint:
    value: None
trainer/val_check_interval:
    value: 1
